package io.nova.core;

public class KeyCodes {

    public static final int
            NV_HAT_CENTERED   = 0,
            NV_HAT_UP         = 1,
            NV_HAT_RIGHT      = 2,
            NV_HAT_DOWN       = 4,
            NV_HAT_LEFT       = 8,
            NV_HAT_RIGHT_UP   = (NV_HAT_RIGHT | NV_HAT_UP),
            NV_HAT_RIGHT_DOWN = (NV_HAT_RIGHT | NV_HAT_DOWN),
            NV_HAT_LEFT_UP    = (NV_HAT_LEFT  | NV_HAT_UP),
            NV_HAT_LEFT_DOWN  = (NV_HAT_LEFT  | NV_HAT_DOWN);

    /** The unknown key. */
    public static final int NV_KEY_UNKNOWN = -1;

    /** Printable keys. */
    public static final int
            NV_KEY_SPACE         = 32,
            NV_KEY_APOSTROPHE    = 39,
            NV_KEY_COMMA         = 44,
            NV_KEY_MINUS         = 45,
            NV_KEY_PERIOD        = 46,
            NV_KEY_SLASH         = 47,
            NV_KEY_0             = 48,
            NV_KEY_1             = 49,
            NV_KEY_2             = 50,
            NV_KEY_3             = 51,
            NV_KEY_4             = 52,
            NV_KEY_5             = 53,
            NV_KEY_6             = 54,
            NV_KEY_7             = 55,
            NV_KEY_8             = 56,
            NV_KEY_9             = 57,
            NV_KEY_SEMICOLON     = 59,
            NV_KEY_EQUAL         = 61,
            NV_KEY_A             = 65,
            NV_KEY_B             = 66,
            NV_KEY_C             = 67,
            NV_KEY_D             = 68,
            NV_KEY_E             = 69,
            NV_KEY_F             = 70,
            NV_KEY_G             = 71,
            NV_KEY_H             = 72,
            NV_KEY_I             = 73,
            NV_KEY_J             = 74,
            NV_KEY_K             = 75,
            NV_KEY_L             = 76,
            NV_KEY_M             = 77,
            NV_KEY_N             = 78,
            NV_KEY_O             = 79,
            NV_KEY_P             = 80,
            NV_KEY_Q             = 81,
            NV_KEY_R             = 82,
            NV_KEY_S             = 83,
            NV_KEY_T             = 84,
            NV_KEY_U             = 85,
            NV_KEY_V             = 86,
            NV_KEY_W             = 87,
            NV_KEY_X             = 88,
            NV_KEY_Y             = 89,
            NV_KEY_Z             = 90,
            NV_KEY_LEFT_BRACKET  = 91,
            NV_KEY_BACKSLASH     = 92,
            NV_KEY_RIGHT_BRACKET = 93,
            NV_KEY_GRAVE_ACCENT  = 96,
            NV_KEY_WORLD_1       = 161,
            NV_KEY_WORLD_2       = 162;

    /** Function keys. */
    public static final int
            NV_KEY_ESCAPE        = 256,
            NV_KEY_ENTER         = 257,
            NV_KEY_TAB           = 258,
            NV_KEY_BACKSPACE     = 259,
            NV_KEY_INSERT        = 260,
            NV_KEY_DELETE        = 261,
            NV_KEY_RIGHT         = 262,
            NV_KEY_LEFT          = 263,
            NV_KEY_DOWN          = 264,
            NV_KEY_UP            = 265,
            NV_KEY_PAGE_UP       = 266,
            NV_KEY_PAGE_DOWN     = 267,
            NV_KEY_HOME          = 268,
            NV_KEY_END           = 269,
            NV_KEY_CAPS_LOCK     = 280,
            NV_KEY_SCROLL_LOCK   = 281,
            NV_KEY_NUM_LOCK      = 282,
            NV_KEY_PRINT_SCREEN  = 283,
            NV_KEY_PAUSE         = 284,
            NV_KEY_F1            = 290,
            NV_KEY_F2            = 291,
            NV_KEY_F3            = 292,
            NV_KEY_F4            = 293,
            NV_KEY_F5            = 294,
            NV_KEY_F6            = 295,
            NV_KEY_F7            = 296,
            NV_KEY_F8            = 297,
            NV_KEY_F9            = 298,
            NV_KEY_F10           = 299,
            NV_KEY_F11           = 300,
            NV_KEY_F12           = 301,
            NV_KEY_F13           = 302,
            NV_KEY_F14           = 303,
            NV_KEY_F15           = 304,
            NV_KEY_F16           = 305,
            NV_KEY_F17           = 306,
            NV_KEY_F18           = 307,
            NV_KEY_F19           = 308,
            NV_KEY_F20           = 309,
            NV_KEY_F21           = 310,
            NV_KEY_F22           = 311,
            NV_KEY_F23           = 312,
            NV_KEY_F24           = 313,
            NV_KEY_F25           = 314,
            NV_KEY_KP_0          = 320,
            NV_KEY_KP_1          = 321,
            NV_KEY_KP_2          = 322,
            NV_KEY_KP_3          = 323,
            NV_KEY_KP_4          = 324,
            NV_KEY_KP_5          = 325,
            NV_KEY_KP_6          = 326,
            NV_KEY_KP_7          = 327,
            NV_KEY_KP_8          = 328,
            NV_KEY_KP_9          = 329,
            NV_KEY_KP_DECIMAL    = 330,
            NV_KEY_KP_DIVIDE     = 331,
            NV_KEY_KP_MULTIPLY   = 332,
            NV_KEY_KP_SUBTRACT   = 333,
            NV_KEY_KP_ADD        = 334,
            NV_KEY_KP_ENTER      = 335,
            NV_KEY_KP_EQUAL      = 336,
            NV_KEY_LEFT_SHIFT    = 340,
            NV_KEY_LEFT_CONTROL  = 341,
            NV_KEY_LEFT_ALT      = 342,
            NV_KEY_LEFT_SUPER    = 343,
            NV_KEY_RIGHT_SHIFT   = 344,
            NV_KEY_RIGHT_CONTROL = 345,
            NV_KEY_RIGHT_ALT     = 346,
            NV_KEY_RIGHT_SUPER   = 347,
            NV_KEY_MENU          = 348,
            NV_KEY_LAST          = NV_KEY_MENU;
}